# Generated by Django 2.2.28 on 2026-03-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamerate_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogame',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
