# Generated by Django 2.2.28 on 2026-03-14 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamerate_app', '0004_alter_review_rating_alter_review_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='videogame',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
