# Generated by Django 2.2.28 on 2026-03-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamerate_app', '0005_auto_20260314_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videogame',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
